### ISSUE TITLE
dio log every line have '<…>'

### ISSUE THREAD

**Issue by huahua8893** [Frezyx/talker#105]
Hi all, new user with talker and have a question, I'm using TalkerDioLogger like this:
![image](https://user-images.githubusercontent.com/10332761/229350421-3790dddc-77ec-481a-bb82-1d65e4b7f297.png)

The log looks like this:

![image](https://user-images.githubusercontent.com/10332761/229350474-bb9e5ddc-6b3d-4450-8000-02818efda092.png)

every single line has a '<…>', is that a problem or I'm missing some settings of talker? Thank you.

**Comment by Frezyx** [comment]
Hello @huahua8893 !
Sorry for a long waiting. 

Which platform are you working with ?

And check [this point](https://github.com/Frezyx/talker/tree/master#%EF%B8%8F-log-messages-integrity) in documentation 
https://github.com/Frezyx/talker/tree/master#%EF%B8%8F-log-messages-integrity

**Comment by Frezyx** [comment]
And check this issue 
https://github.com/Frezyx/talker/issues/104
