### ISSUE TITLE
Support share_plus 7.0.0

### ISSUE THREAD

**Issue by Ciock** [Frezyx/talker#106]
**Is your feature request related to a problem? Please describe.**

> Because talker_flutter 2.4.3 depends on share_plus ^6.3.1 and no versions of talker_flutter match >2.4.3 <3.0.0, talker_flutter ^2.4.3 requires share_plus ^6.3.1.

[share_plus](https://pub.dev/packages/share_plus)

**Comment by Frezyx** [comment]
Resolved in (3.0.0 Release)[https://github.com/Frezyx/talker/pull/108]
Please reopen the issue if you have any further questions or if the bug has not been fixed ❤️
