### ISSUE TITLE
Improve talker_bloc_logger by adding onChange, onCreate, onClose

### ISSUE THREAD

**Issue by MiniSuperDev** [Frezyx/talker#109]
Hello,

It would be great if you added support for these events, especially since without them no cubit logs.

https://pub.dev/documentation/bloc/latest/bloc/BlocObserver-class.html

**Comment by Frezyx** [comment]
@MiniSuperDev hello !
Thank you for this issue. Yes, this functionality will be great. 

You can implement this if you have enough time. This project open for new contributors

**Comment by Frezyx** [comment]
Resolved in https://github.com/Frezyx/talker/pull/162
