### ISSUE TITLE
RenderFlex overflow error while using the TalkerScreen.

### ISSUE THREAD

**Issue by VladPobidash** [Frezyx/talker#113]
**Describe the bug**
When I've included the `TalkerScreen` into my page screen I've gotten the `RenderFlex overflow` error.

**To Reproduce**
Here is my [source code](https://github.com/VladPobidash/cryptoys)
1. Add and open the `TalkerScreen` widget on any page
2. Include the following code on the `main.dart`:
   `FlutterError.onError = (details) => GetIt.I<Talker>().handle(details.exception, details.stack);`
3. See the error

**Expected behavior**
No `RenderFlex overflow` errors while using the `TalkerScreen`.

**Screenshots**
<img width="2253" alt="image" src="https://github.com/Frezyx/talker/assets/54101242/ea085050-fd11-41df-a8b9-06454d77ca8c">
<img width="283" alt="image" src="https://github.com/Frezyx/talker/assets/54101242/cdd2b21c-4777-4bb6-a276-19fd0d875f25">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. 13.4]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone14 Pro Max]
 - OS: [e.g. iOS16.4]

**Comment by Frezyx** [comment]
Hello @VladPobidash 👋
Thank you for this issue! 

I think this bug occurs because the **TextStyle** of this **Text** depends on the **theme** style. 
We can provide a clear definition of the TextStyle **fontSize** for it.
