### ISSUE TITLE
Stack trace not printed when throwing String

### ISSUE THREAD

**Issue by westito** [Frezyx/talker#122]
**Describe the bug**
Stack trace not printed when throwing String (or any type except Error/Exception).

**To Reproduce**
Call `talker.log('message', exception: 'Exception message', stackTrace: stack);` in try-catch

**Expected behavior**
Prints stack trace

**Solution?**
`String` exceptions are mapped to `TalkerLog` (in `error_handler.dart:8`) and this interface not includes `stackTrace` in its`generateTextMessage()` function.

**Comment by Frezyx** [comment]
Hello @westito ! 
Thank you for this issue
It is bug definitely. I'll get to it soon

**Comment by Frezyx** [comment]
Fixed in https://github.com/Frezyx/talker/pull/199
