### ISSUE TITLE
LogLevel.info has lower priority than debug and verbose 

### ISSUE THREAD

**Issue by cselti** [Frezyx/talker#123]
**Describe the bug**
In most logging libraries (like [Logger](https://pub.dev/packages/logger) or every Java logging libs) the `info` has higher priority than `debug` or `verbose` (or other libraries use `trace` at this level).

I think the `good` level should be higher than `debug` or `verbose`, but I'm not sure in that (this log level doesn't exist in other logger libs).

**Expected behavior**
The LogLevel.info doesn't show the debug and verbose log messages.

**Comment by Frezyx** [comment]
Hello @cselti 👋
Yes, I think you're right. 
I forgot about this point, and the log levels should have been sorted a long time ago.

About LogLevel.good, I agree as well. 
It was implemented before the talker had the ability to make custom logs.
And now this LogLevel seems useless

**Comment by cselti** [comment]
Hi @Frezyx 
Is it possible to publish this fix to talker_logger@2.2.1 with talker_flutter@2.4.1?
My other project can't use talker v3+ because of dependency collision 😕 .
Thanks in advance,
Adrian

**Comment by Frezyx** [comment]
Hello @cselti ! 
Can you provide screenshots? 
Which problems you receive ?

**Comment by cselti** [comment]
Hi @Frezyx ,
the same problem - the verbose and debug has higher priority than the info.

In the `packages/talker_logger/lib/src/models/log_level/log_level.dart`
``` dart
/// List of levels sorted by priority
final logLevelPriorityList = [
  LogLevel.critical,
  LogLevel.error,
  LogLevel.warning,
  LogLevel.debug,
  LogLevel.verbose,
  LogLevel.info,
  LogLevel.fine,
  LogLevel.good
];
```

**Comment by Frezyx** [comment]
Sorry mate. I'm talking about migration issues. 
Why you can't use talker versions >3.0.0 ?

**Comment by cselti** [comment]
Hi, we have a lot of dependencies, that are mostly out-dated 😕. But I don't have time at the moment to update everything because it's need code modifications too. But no problem, I have created a fork and I add that as a git dependency to my project 🙂
