### ISSUE TITLE
There is a problem with the layout on the tolker screen

### ISSUE THREAD

**Issue by BDemetrix** [Frezyx/talker#125]
- talker_flutter: ^3.1.5
 - OS: Android emulator (pixel API 34)

![Screenshot 2023-07-09 at 19 31 18](https://github.com/Frezyx/talker/assets/64604742/6cde869f-4e45-4188-aac6-59d51a3cdd8a)

**Comment by Frezyx** [comment]
Hello @BDemetrix 👋
Thanks a lot for this issue reporting! 
It's definitely a bug. 

To solve this, we will need to specify the exact size of the text in the search TextField in talker_flutter

**Comment by Frezyx** [comment]
Hello @BDemetrix !
This bug was solved in [new 3.1.7 release](https://pub.dev/packages/talker_flutter) of talker_flutter
