### ISSUE TITLE
Member not found: 'MediaQuery.paddingOf'

### ISSUE THREAD

**Issue by n0ks** [Frezyx/talker#133]
After updating the pubspec dependencies, i think the package probably broke after the #131 

![image](https://github.com/Frezyx/talker/assets/22434056/abd9810c-373c-449d-a856-195da9f241f9)

I'm using flutter version 3.7.12 and this method inside the MediaQuery is probably something on the newer versions.

This is probably a breaking change

**Comment by Frezyx** [comment]
Hello, @n0ks !
My bad, I didn’t check from which version of Flutter this functionality comes.

**Comment by Frezyx** [comment]
This bug must be fixed

**Comment by Frezyx** [comment]
Fix available in [3.1.12 version ](https://pub.dev/packages/talker_flutter)
