### ISSUE TITLE
Support web platform download logs.txt file  

### ISSUE THREAD

**Issue by Kabak-Siarhei** [Frezyx/talker#142]
Edit class TalkerScreen function 
<img width="691" alt="image" src="https://github.com/Frezyx/talker/assets/80242571/0e1fa227-1e5e-48f6-9d01-034a7f92041a">

Add function in class TalkerScreenController
<img width="820" alt="image" src="https://github.com/Frezyx/talker/assets/80242571/b76f0231-e842-4d1a-b97e-eea6b2756420">

**Comment by Frezyx** [comment]
Hello @Kabak-Siarhei !
It will be great if you can contribute this functionality with open pull request

**Comment by Kabak-Siarhei** [comment]
> Hello @Kabak-Siarhei ! It will be great if you can contribute this functionality with open pull request

Can tou add me to this repo ?

**Comment by Frezyx** [comment]
@Kabak-Siarhei you can make fork of this repository and create pull request from your fork with new commits

**Comment by Kabak-Siarhei** [comment]
> @Kabak-Siarhei you can make fork of this repository and create pull request from your fork with new commits

Yes, thx. 
I created PR
