### ISSUE TITLE
Recieve message misprint

### ISSUE THREAD

**Issue by Borteq2** [Frezyx/talker#151]
**Describe the bug**
Eventing message is `Blocname recvie event`

**To Reproduce**
1. Use Bloc.observer like ```Bloc.observer = TalkerBlocObserver(
      talker: talker,
      settings: const TalkerBlocLoggerSettings(
        printEventFullData: false,
        printStateFullData: false,
      ),
    );```
2. Add some event
3. See message with misprint

**Expected behavior**
Message is `Blocname recieve event`, not `recvie`

**Screenshots**
![image](https://github.com/Frezyx/talker/assets/99243818/444e5955-8572-40f3-81d5-750a3d5cfad8)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: talker_bloc_logger 2.0.0

**Comment by Frezyx** [comment]
Hello @Borteq2 👋
Thank you for this issue! 

```recvie``` is a real typo. 

We will need to fix this mistake. Can you pls open a pull request with that fix?
