### ISSUE TITLE
Не выводит логи в дебаг консоль на macos

### ISSUE THREAD

**Issue by babayanta1994** [Frezyx/talker#165]
При отладке приложения с целевой платформой macos, перестали выводиться логи в  консоль отладки. Т.е. всё что вывожу принтом выводится а всё что вывожу Talker'ом нет. Появился этот баг пару дней назад. 
**Macos sanoma 14.1.1 
Flutter 3.16.2
Dart 3.2.2
talker_flutter 3.5.6**

**Comment by Frezyx** [comment]
Привет! Спасибо за сообщение об этой ошибке.
Пока не могу сказать почему так происходит, буду разбираться с этой ошибкой в ближайшем будущем.
