### ISSUE TITLE
TalkerScreen does not respect configured LogLevel setting

### ISSUE THREAD

**Issue by rho-cassiopeiae** [Frezyx/talker#168]
**Describe the bug**
`TalkerScreen` does not respect configured `LogLevel` while console logs _do_ respect it.

I initialize a global `Talker` instance like this:
```dart
late final Talker logger;

void main() {
  logger = TalkerFlutter.init(
    logger: TalkerLogger(
      settings: TalkerLoggerSettings(level: LogLevel.warning),
    ),
  );

  runApp(const App());
}
```
And create a `TalkerScreen` like this:
```dart
showDialog(
  context: context,
  builder: (_) => SimpleDialog(
    children: [
      SizedBox(
        width: 1000,
        height: 600,
        child: TalkerScreen(
          appBarTitle: 'Logs',
          talker: logger, // same global instance
        ),
      ),
    ],
  ),
);
```

When running, I can see that console logs are outputted correctly – only warnings and more severe, but `TalkerScreen` still shows all logs, even those that should be filtered out.

**Expected behavior**
Both console and `TalkerScreen` correctly filter out logs based on configured `LogLevel`.

**Additional context**
Flutter Web
talker_flutter: 3.5.6

**Comment by mylukin** [comment]
I also encountered this problem
