### ISSUE TITLE
Text color not always visible

### ISSUE THREAD

**Issue by XanderD99** [Frezyx/talker#174]
**Describe the bug**
TalkerScreenTheme textColor  is not used consistently throughout the TalkerScreen page

**To Reproduce**
1. Create talkerscreen with white background
2. go to talkerscreen
3. you'll see that not all text is readable

**Expected behavior**
Text to be readable when background is not dark

**Screenshots**
<img width="758" alt="Screenshot 2024-01-15 at 16 50 39" src="https://github.com/Frezyx/talker/assets/36887752/10a68e75-8326-47df-8d6a-fc5e6dd19309">
<img width="758" alt="Screenshot 2024-01-15 at 16 50 32" src="https://github.com/Frezyx/talker/assets/36887752/1dce44cb-4a5b-47f9-95a0-dea666c2d879">

**Comment by XanderD99** [comment]
code snippet: 
```dart
TalkerScreen(
  talker: talker,
  theme: TalkerScreenTheme(
    backgroundColor: context.colorScheme.background,
    textColor: context.colorScheme.onBackground,
    cardColor: context.colorScheme.surface,
  ),
);
```

**Comment by Frezyx** [comment]
Hello @XanderD99 ! 
Thank you for this issue, I will check it in near future
