### ISSUE TITLE
The stack trace is not printed when thrown

### ISSUE THREAD

**Issue by laterdayi** [Frezyx/talker#183]
```
talker.error(message, exception, stackTrace)
info(message, exception, stackTrace)
debug(message, exception, stackTrace)
```

![image](https://github.com/Frezyx/talker/assets/122137647/0d092a44-06c0-46c9-9dc1-e4a34ca6be49)
Print without exception and stackTrace messages

**Comment by Frezyx** [comment]
Fixed in https://github.com/Frezyx/talker/pull/199
