### ISSUE TITLE
Unsupported operation: StdIOUtils._getStdioOutputStream

### ISSUE THREAD

**Issue by tas-unn** [Frezyx/talker#185]
**Describe the bug**
I've tried to use gorouter with this package.

**To Reproduce**
1) This is a short version of my code
```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:talker_flutter/talker_flutter.dart';

void main() async {
  GoRouter.optionURLReflectsImperativeAPIs = true;
  runApp(const RouteIt());
}

class RouteIt extends StatefulWidget {

  const RouteIt({super.key});


  @override
  State<RouteIt> createState() => _RouteItState();
}

class _RouteItState extends State<RouteIt> {

  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    final talker = Talker();
    final GoRouter _router = GoRouter(
      observers: [TalkerRouteObserver(talker)],
      routes: <GoRoute>[
        GoRoute(

            routes: <GoRoute>[
            ],

            path: "/",
            builder: (BuildContext context1, state1) =>
                                Text("!")

        )
      ],
    );
    return
      MaterialApp.router(

          routerDelegate: _router.routerDelegate,
          routeInformationParser: _router.routeInformationParser,
          routeInformationProvider: _router.routeInformationProvider,
          title:"111",
          debugShowCheckedModeBanner: false,
          );


  }

}
```

2) If i comment observers line - it works fine, but Talker is not work)

All packages have been updated to the latest version 
```
  go_router: ^13.1.0
  talker_flutter: ^4.0.0
```

**Comment by cfsbhawkins** [comment]
I am getting the same issue after upgrading from v3 on a flutter web project. I also noticed that with v4 web is no longer listed as a platform. Will have to revert back to v3.

**Comment by sarp86** [comment]
Same Problem we also have - any solutions?

**Comment by cfsbhawkins** [comment]
> Same Problem we also have - any solutions?

Revert to v3

**Comment by Frezyx** [comment]
Hello everyone! 
Please check out [this article](https://github.com/Frezyx/talker?tab=readme-ov-file#setup) in docs 

Talker uses different log methods for different platforms with **TalkerFlutter.init()** constructor 
By default - **stdout.writeln**
For web - **print** (because the stdout.writeln method from io package that not available in web)

**Comment by Frezyx** [comment]
All you need to fix this issue - just replace **Talker()** constructor with **TalkerFlutter.init()**
