### ISSUE TITLE
Ошибки в логике настроек Talker Screen в новой версии.

### ISSUE THREAD

**Issue by K1yoshiSho** [Frezyx/talker#186]
В настройках стандартно три функции: вкл/выкл самого логирования в общем, в консоли и сбор истории.
В новых версиях я заметил поменялась логика в configure, а точнее не задается ранее значения late, а как будто по-новому все.
Из-за этого получаются некоторые баги и/или недочеты:
1) Если отключить только историю, то он удаляет все, что было ранее, что не хотелось бы. То он отключает и логирование в консоли тоже.
2) Если отключить логирование в консоли, то он опять же удаляет все что было ранее из истории, и после обратного включения перестает хэндлить в консоли, но история работает.
3) Если отключить в общем, то так же, удаляет все что было, и после обратного включения перестает хэндлить в консоли.

Так же, после этих удалений появляются косяки в UI на основной странице: как пустые боксы за место GroupButtons и так далее.

**Comment by K1yoshiSho** [comment]
Кажется исправил все ошибки. Надо перепроверить. Открыл pr: https://github.com/Frezyx/talker/pull/187
@Frezyx

**Comment by Frezyx** [comment]
Привет @K1yoshiSho 👋
Спасибо большое за фикс! Действительно недоглядел при релизе.
