### ISSUE TITLE
please update depends talker ^4.0.1 for talker_http_logger 0.1.0-dev

### ISSUE THREAD

**Issue by huanguan1978** [Frezyx/talker#188]
**Describe the bug**

Resolving dependencies... (5.7s)
Because talker_http_logger 0.1.0-dev.1 depends on talker ^3.0.0 and no versions of talker_http_logger match >0.1.0-dev.1 <0.2.0, talker_http_logger ^0.1.0-dev.1
  requires talker ^3.0.0.
So, because  depends on both talker ^4.0.1 and talker_http_logger ^0.1.0-dev.1, version solving failed.

**Comment by Frezyx** [comment]
Hello @huanguan1978 ! 
Thank you for this issue. I will update talker_http_logger dependencies in near future

**Comment by JPFrancoia** [comment]
Could we update the dependency please?

**Comment by Frezyx** [comment]
Hello @huanguan1978 @JPFrancoia !
Sorry for the delay. Now you can use version `0.1.0-dev.3` of the library.
