### ISSUE TITLE
can not print dio log 

### ISSUE THREAD

**Issue by sdjwj1118** [Frezyx/talker#196]
Use Dart 5.4.1 talker_dio_logger 4.0.2 
can not print diolog 
![image](https://github.com/Frezyx/talker/assets/33438073/a07303c0-6a62-412e-b5ca-67145e38ba2c)

**Comment by nyan-ucsp** [comment]
use 2.4.0, new 4.0 is not working

**Comment by Frezyx** [comment]
Hello everyone! 
The discussion on this issue is now underway in related [issue](https://github.com/Frezyx/talker/issues/200)
