### ISSUE TITLE
[talker_bloc_logger] Since upgrading to versions 4.x.x, not seeing any logs anymore (Flutter 3.19.3)

### ISSUE THREAD

**Issue by WieFel** [Frezyx/talker#200]
**Describe the bug**
I just upgraded the `talker_bloc_logger` package from version `2.4.0` to latest `4.0.3`, and noticed that suddenly I don't see any bloc logs anymore. I also recently upgraded to latest Flutter version `3.19.3`, so it could be related.

**To Reproduce**
1. Install Flutter version 3.19.3
2. Install talker_bloc_logger version 4.0.3
3. Start the app, and notice that there are no bloc logs

**Expected behavior**
I would expect the logs to just show normally

**Smartphone (please complete the following information):**
 - Device: iOS Simulator + Android Emulator
 - OS: iOS/Android

**Comment by Frezyx** [comment]
Hello @WieFel ! 
Can you provide info about your code editor ?

**Comment by WieFel** [comment]
Sure!

<details>
<summary>Android Studio version info</summary>

```
Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 21, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    Dart (232.10305)
    com.bloc.intellij_generator_plugin (3.4.0)
    com.github.copilot (1.5.0.5148)
    io.flutter (78.2.2)

```

</details>

<details>
<summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by AngeloAvv** [comment]
Same behavior with talker_dio_logger

**Comment by davidnwaneri** [comment]
This also happens in talker_dio_logger. Having:
```dart
 _dio.interceptors.add(
        TalkerDioLogger(
          settings: const TalkerDioLoggerSettings(
            printRequestHeaders: true,
          ),
        ),
      );
```

**Comment by quentin996007** [comment]
any update?

**Comment by sfcecy7i** [comment]
still not resolved?

**Comment by Frezyx** [comment]
Hello everyone! 
To prevent issues with log output, you need to pass "talker" as a parameter to all third-party libraries in the "talker" ecosystem.

**You can use the following code for the TalkerDioLogger:**
```dart    
final talker = TalkerFlutter.init();
    _dio = Dio();
    _dio.interceptors.add(
      TalkerDioLogger(
        talker: talker,
      ),
    );
```

**Why is this happening?**
[❗️ Log messages integrity](https://github.com/Frezyx/talker?tab=readme-ov-file#%EF%B8%8F-log-messages-integrity)

**Comment by Frezyx** [comment]
And now I move back default Talker output method for mobile platforms.
Please check how TalkerDioLogger works in your applications with version 4.1.4.

```yaml
  talker_flutter: ^4.1.4
  talker_dio_logger: ^4.1.4
  talker_bloc_logger: ^4.1.4
```
