### ISSUE TITLE
[talker_flutter] Update group_button dep to 5.3.4

### ISSUE THREAD

**Issue by II11II** [Frezyx/talker#204]
**Describe the bug**
Error (Xcode): ../../.pub-cache/hosted/pub.dev/group_button-5.3.3/lib/src/group_button_item.dart:92:9: Error: No named parameter with the name 'primary'.

The usage of the deprecated field is replaced with a new API field from 5.3.4 in the group_button package, but talker_flutter depends on the group_button 5.3.3 which uses the deprecated field.

It throws a compile time error while building the latest Flutter version because the primary is field removed there.

** To reproduce **: create app using the below dependencies and compile it:
Flutter version: 3.19.2
talker_flutter: ^4.1.0

**Comment by Frezyx** [comment]
Hello @II11II ! 
This issue was resolved in new [4.1.2 version](https://pub.dev/packages/talker)
