### ISSUE TITLE
Console logs missing exception/error info

### ISSUE THREAD

**Issue by Zekfad** [Frezyx/talker#205]
**Describe the bug**
Console logs missing exception/error info in verbose level.

**To Reproduce**
1. Use `talker.verbose('Message', Exception(), StackTrace.current)`;
2. Message and stack trace is present, but error is swallowed in console output.
3. TalkerScreen displays error information.

**Expected behavior**
Error should be printed as well.

**Screenshots**

**Desktop (web):**
 - OS: Windows 10
 - Browser Chrome
 - Version 124.0.6367.8

**Additional context**
To fix the problem `TalkerData#generateTextMessage` (talker/lib/src/models/talker_data.dart) should also include `$displayError` like so:
```dart
  String generateTextMessage() {
    return '$displayTitleWithTime$message$displayError$displayStackTrace';
  }
```

**Comment by Frezyx** [comment]
@Zekfad Hello! 
This issue was resolved in new [4.1.1 version](https://pub.dev/packages/talker)
