### ISSUE TITLE
Support share_plus ^8.0.0

### ISSUE THREAD

**Issue by KoheiKanagu** [Frezyx/talker#206]
**Is your feature request related to a problem? Please describe.**

The [share_plus](https://pub.dev/packages/share_plus/versions) version ^8.0.0 has been released

**Comment by Frezyx** [comment]
Hello @KoheiKanagu !
This issue was resolved in new [4.1.3 version](https://pub.dev/packages/talker)

**Comment by KoheiKanagu** [comment]
Thanks!
