### ISSUE TITLE
How can we use the Talker with release mode?

### ISSUE THREAD

**Issue by cogivn** [Frezyx/talker#216]
**Is your feature request related to a problem? Please describe.**
When sign the application with release mode. I don't want to print sensitive data in console but want to keep send logs to Firebase Crashlytics via Talker. Now on Talker library has `enable` property to control it but when we disable then all talker features will be disabled. 

**Describe the solution you'd like**
 Do we have any ways to keep the Talker process still running when `enable=fasle` but do not print logs in console for release mode or keep the TalkerObserver still running even the talker settings is disabled?

**Comment by Frezyx** [comment]
Hello @cogivn ! 
You can set **useConsoleLogs** field for these purposes
https://github.com/Frezyx/talker/tree/master/packages/talker#%EF%B8%8F-customization

```dart
final talker = TalkerFlutter.init(
  settings: TalkerSettings(
    enabled: true,
    useConsoleLogs: kDebugMode,
  ),
  observer: SentryTalkerObserver(),
);
```

**Comment by AhmedEzio47** [comment]
@Frezyx The enabled and useConsoleLogs are true by default, but I still don't get any logs in the TalkerScreen in release mode. Could be please explain the reason?
