### ISSUE TITLE
Add multiple TalkerObserver in TalkerFlutter.init()

### ISSUE THREAD

**Issue by venkata-reddy-dev** [Frezyx/talker#227]
```dart
TalkerFlutter.init(
  observers: [
     SomeTalkerObserver(),
     SomeOtherTalkerObserver(),
  ],
)
```

**Comment by Frezyx** [comment]
Hello @venkata-reddy-dev !
Previously, it was possible to specify a list of observers in the library. 
But then I found architectural solution in the BloC library 

Felix answer: https://github.com/felangel/bloc/issues/3852

And now you can write your own MultiTalkerObserver
