### ISSUE TITLE
Add color customization for TalkerLog in TalkerScreen

### ISSUE THREAD

**Issue by Rodsevich** [Frezyx/talker#252]
**Is your feature request related to a problem? Please describe.**
If you create a custom log (suppose a metric/setting/etc) you must attain to the default grey color because of limitations on the enums Talker uses.

**Describe the solution you'd like**
I'd love you can define another property in the TalkerLog for enforcing the color for those logs.

**Describe alternatives you've considered**
I have no way of tweaking the behavior as a user, the only alternative was to forfeit the color I need.

**Additional context**
Enums can't be extended, but sealed classes can. Taking in consideration that [enums will never be extended](https://github.com/dart-lang/language/issues/2733#issuecomment-1358267901) and custom logs are a thing needed, why can't we change to classes approach instead of enums?

**Comment by Mooyeee** [comment]
This was actually something I was thinking about too, I may play around a bit when I get some time since it would be very useful.

**Comment by Frezyx** [comment]
Hello @Rodsevich @Mooyeee ✋🏻 
We have already started working on this functional. 
You can check this https://github.com/Frezyx/talker/pull/272 PR to make review.

**Comment by Frezyx** [comment]
Hello @Rodsevich @Mooyeee! 
We have fixed this issue in this PR https://github.com/Frezyx/talker/pull/272
This fixes available in [4.5.0](https://pub.dev/packages/talker) package version
