### ISSUE TITLE
no color change for route enum

### ISSUE THREAD

**Issue by damianololo** [Frezyx/talker#259]
when changing the color for the route enum there is no reaction in the console. other colors change correctly

**To Reproduce**
`final talker = TalkerFlutter.init(
  settings: TalkerSettings(
    colors: {
      TalkerLogType.route: AnsiPen()..yellow(), 
    },
  ),
);`

**Expected behavior**
Color should be yellow. 

**Screenshots**
![image](https://github.com/user-attachments/assets/cb34a846-ca23-4d3a-9475-f62e1546298e)

**Comment by Frezyx** [comment]
Hello @damianololo ! 
We have fixed this issue in this PR https://github.com/Frezyx/talker/pull/272
This fixes available in [4.5.0](https://pub.dev/packages/talker) package version

**Comment by damianololo** [comment]
Thanks for update
