### ISSUE TITLE
When we open TalkerScreen, how can we make the logs initially collapsed?

### ISSUE THREAD

**Issue by zhake555** [Frezyx/talker#273]

**Comment by Frezyx** [comment]
Hello @zhake555 👋
Right now this functionality is not exist in TalkerScreen
Do you want to suggest such an improvement?

**Comment by zhake555** [comment]
@Frezyx

Да это было бы удобно. Если все запросы будут в развернутом виде сложно найти необходимый запрос. Каждый раз когда открываю TalkerScreen я нажимаю "Collapse logs". Думаю это должно настраиваться при вызове TalkerScreen. Примерно так TalkerScreen(talker: getIt<Talker>(), initiallyCollapsed: true) типа так))

**Comment by Ilushnik** [comment]
I've made a pull request #292
