### ISSUE TITLE
Feature request: Add name filter for log

### ISSUE THREAD

**Issue by a1573595** [Frezyx/talker#280]
**Is your feature request related to a problem? Please describe.**
When there are various events in the log, it is not easy to check, refer to Proposal #279, add a filter with custom name to make customized Logger flexible.

**Describe the solution you'd like**
Add a filter to specify the name of the log to be output.
```dart
final talker = Talker(
    settings: const TalkerSettings(
      /// Add a custom filter
      nameFilterList : [ "Cloud message", "Google Analytics", ...],
      ...
    ),
    ///etc...
  );
```

**Describe alternatives you've considered**
As an alternative, I could manually add the filter for name or tag in the log message, but this becomes cumbersome and doesn't provide the same level of integration or convenience that a dedicated name parameter would offer.

Adding the ability to specify custom tag filters will allow for better log management, especially in large applications.

**Comment by Frezyx** [comment]
Hello @a1573595 ! 👋
Right now this functionality included in [TalkerFilter](https://github.com/Frezyx/talker/blob/master/packages/talker/lib/src/filter.dart)

You can provide any log **titles** or log **types** in **TalkerFilter** constructor and then talker will not show and store relevant logs. 
```dart
final filter = BaseTalkerFilter(
    titles: ['Error'],
    types: [Exception],
);

final talker = Talker(filter: filter);
talker.info('Any info message'); // Do nothing
```

Does this solve your problem?

**Comment by a1573595** [comment]
> Hello @a1573595 ! 👋 Right now this functionality included in [TalkerFilter](https://github.com/Frezyx/talker/blob/master/packages/talker/lib/src/filter.dart)
> 
> You can provide any log **titles** or log **types** in **TalkerFilter** constructor and then talker will not show and store relevant logs.
> 
> ```dart
> final filter = BaseTalkerFilter(
>     titles: ['Error'],
>     types: [Exception],
> );
> 
> final talker = Talker(filter: filter);
> talker.info('Any info message'); // Do nothing
> ```
> 
> Does this solve your problem?

Is the filter title for the log level rather than the type of event? For example, I only want to track Bluetooth, which may contain multiple levels, such as info, warning and error.

**Comment by Frezyx** [comment]
> > Hello @a1573595 ! 👋 Right now this functionality included in [TalkerFilter](https://github.com/Frezyx/talker/blob/master/packages/talker/lib/src/filter.dart)
> > You can provide any log **titles** or log **types** in **TalkerFilter** constructor and then talker will not show and store relevant logs.
> > ```dart
> > final filter = BaseTalkerFilter(
> >     titles: ['Error'],
> >     types: [Exception],
> > );
> > 
> > final talker = Talker(filter: filter);
> > talker.info('Any info message'); // Do nothing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this solve your problem?
> 
> Is the filter title for the log level rather than the type of event? For example, I only want to track Bluetooth, which may contain multiple levels, such as info, warning, and error.

Yes, filter currently work with types and titles of logs.  
For example you can show only your custom Bluetooth logs in console.

In this case you need to create [custom log class ](https://github.com/Frezyx/talker?tab=readme-ov-file#custom-logs)
And send all Bluetooth logs with talker.**logCustom()** method

**Comment by Frezyx** [comment]
@a1573595 you can use example code below:

```dart
class BluetoothLog extends TalkerLog {
  BluetoothLog(String message) : super(message);

  /// Your custom log title
  @override
  String get title => 'bluetooth';

  /// Your custom log color
  @override
  AnsiPen get pen => AnsiPen()..green();
}

void main() {
  final talker = Talker(
    filter: BaseTalkerFilter(
      types: [BluetoothLog],
    ),
  );
  talker.logCustom(BluetoothLog('Connected to device id: {deviceId}'));
  talker.info('Other logs');
}
```

Console output:
<img width="629" alt="image" src="https://github.com/user-attachments/assets/94ff7d76-2165-462c-9a91-112cf1f997a6">

**Comment by a1573595** [comment]
> @a1573595 you can use example code below:
> 
> ```dart
> class BluetoothLog extends TalkerLog {
>   BluetoothLog(String message) : super(message);
> 
>   /// Your custom log title
>   @override
>   String get title => 'bluetooth';
> 
>   /// Your custom log color
>   @override
>   AnsiPen get pen => AnsiPen()..green();
> }
> 
> void main() {
>   final talker = Talker(
>     filter: BaseTalkerFilter(
>       types: [BluetoothLog], //or titles:['bluetooth']
>     ),
>   );
>   talker.logCustom(BluetoothLog('Connected to device id: {deviceId}'));
>   talker.info('Other logs');
> }
> ```
> 
> Console output: <img alt="image" width="629" src="https://private-user-images.githubusercontent.com/40857927/388093214-94ff7d76-2165-462c-9a91-112cf1f997a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjMzNDcsIm5iZiI6MTczMjc2MzA0NywicGF0aCI6Ii80MDg1NzkyNy8zODgwOTMyMTQtOTRmZjdkNzYtMjE2NS00NjJjLTlhOTEtMTEyY2YxZjk5N2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAzMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MDNiYzc1ZDdmOWFlOGEzZTQ4ZDQzNWM5Y2IzM2EyNDM2NDM3NzI1YmVkNTgzY2FiODE5OWVlZmVjZDRhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iQBGhWgZkAeWBjcu9Nve246FGL8pS9LlR7J3Ro-0AE0">

Thank you, looks great

**Comment by a1573595** [comment]
> @a1573595 you can use example code below:
> 
> ```dart
> class BluetoothLog extends TalkerLog {
>   BluetoothLog(String message) : super(message);
> 
>   /// Your custom log title
>   @override
>   String get title => 'bluetooth';
> 
>   /// Your custom log color
>   @override
>   AnsiPen get pen => AnsiPen()..green();
> }
> 
> void main() {
>   final talker = Talker(
>     filter: BaseTalkerFilter(
>       types: [BluetoothLog], //or titles:['bluetooth']
>     ),
>   );
>   talker.logCustom(BluetoothLog('Connected to device id: {deviceId}'));
>   talker.info('Other logs');
> }
> ```
> 
> Console output: <img alt="image" width="629" src="https://private-user-images.githubusercontent.com/40857927/388093214-94ff7d76-2165-462c-9a91-112cf1f997a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzgyMjIsIm5iZiI6MTczMjc3NzkyMiwicGF0aCI6Ii80MDg1NzkyNy8zODgwOTMyMTQtOTRmZjdkNzYtMjE2NS00NjJjLTlhOTEtMTEyY2YxZjk5N2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3MTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5N2YxNjI1MWIwMGNlYzkxMmEwMzM3YWE0ODBjNmU5ZTlmNTEwZmE4N2JkMmJmYmIxOTYxMDY2YTBiNTU5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6YEzPz5gdVfOEf_BxF4jfkSrWj_cCt9eLlSUCs4Cgo">

It looks great, can the filter limit the log level, for example, I only want to read the error log of the specified Title.

**Comment by a1573595** [comment]
Ａnother question, if I only want to filter specific Title and Type(maybe LogeLevel), I will currently use "Or" logic. Is there a filtering method with "And" logic?

**Comment by Frezyx** [comment]
@a1573595 Hello! 
Right now LogLevel filtering is not supported by Talker, but supported by talker_logger ``LogLevelFilter``
This filter used as [default](https://github.com/Frezyx/talker/blob/4eec3e12208f896b29d9f74063ab7ddd956a0877/packages/talker_logger/lib/src/filter/loglevel_logger_filter.dart) in TalkerLogger 

If you want to create LogLevel filter for Talker make new issue or PR 🤝
