### ISSUE TITLE
Support for flutter web

### ISSUE THREAD

**Issue by sk92129** [Frezyx/talker#299]
Your flutter plugin does not explicitly indicate that it supports flutter web.
Besides ios and android which I need support, does your plugin support flutter web?

**Comment by Frezyx** [comment]
Hello @sk92129! 
All packages in the talker [ecosystem](https://github.com/Frezyx/talker?tab=readme-ov-file#packages) currently support Flutter web. 
For example you can check our web demo on GitHub Pages https://frezyx.github.io/talker

**Comment by Frezyx** [comment]
But [talker_flutter](https://pub.dev/packages/talker_flutter/score) doesn't currently support WebAssembly (WASM).
This issue will be fixed in future releases of the package.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/ece1b447-aa23-4bfe-b59a-5444539f5d9e" />
