### ISSUE TITLE
Talker card message overlapped by title

### ISSUE THREAD

**Issue by clragon** [Frezyx/talker#38]
**Describe the bug**
Opening the log shows the log items being overlapped by their title.

**To Reproduce**
1. add a TalkerScreen
2. open said screen
3. observe UI weirdness

**Expected behavior**
The item text should be below the title.

**Screenshots**
![image](https://user-images.githubusercontent.com/11785085/171230878-3dc1a112-12a0-44ee-9b21-480af8c606db.png)

**Smartphone:**
 - Device: Galaxy S20
 - OS: Android 12

**Package**:
- talker_flutter 0.12.0

**Comment by Frezyx** [comment]
Hello @clragon 
Thank you for making this issue!
I will fix it soon 😉
