### ISSUE TITLE
Export talker cards

### ISSUE THREAD

**Issue by clragon** [Frezyx/talker#46]
**Is your feature request related to a problem? Please describe.**
I really like this package. It even provides UI to show the logs in which is great.
However, the `TalkerScreen` has a bit too many features for my taste,
and doesnt fit with the design of my app too well.

**Describe the solution you'd like**
It would be nice if the `TalkerDataCard` was exported, so we can build our own screen.

**Describe alternatives you've considered**
I have considered building the entire screen myself as well as the card.
However, with that have to create the colors and the frame, etc. myself.

**Additional context**
(it would also be nice if the icon button inside the cards could be configured via a "trailing" parameter)

**Comment by Frezyx** [comment]
Hello @clragon !
Thank you for the nice words about the package!
I understand what you're talking about. I think it will be wonderful to give the opportunity to customize TalkerScreen as much as possible.

**Comment by Frezyx** [comment]
I will try to find time in the near future to implement this

**Comment by Frezyx** [comment]
I started development towards customization of talker for flutter in the new prerelease. 
In [https://pub.dev/packages/talker_flutter/versions/1.1.0-dev.1](1.1.0-dev.1) you can try TalkerListener )

**Comment by Frezyx** [comment]
Hello @clragon !
You can try TalkerHistoryBuilder and TalkerBuilder widgets in new development package version
https://pub.dev/packages/talker_flutter/versions/1.2.0-dev

**Comment by clragon** [comment]
Hi @Frezyx,
sorry for the late response. unfortunately do these changes not help me.
Trying to add a streambuilder that listens to talker was not the issue I am facing.

I wouldve liked to be able to customize the inbuilt logger screen or cards.
Not a full replacement but options to change or disable some things.

I have in the meantime already made my own complete custom logging screen for talker without the builder widgets. 
They might still be useful for someone else trying to make a completely custom screen.
Thank you for your time though, I will close this issue.
