### ISSUE TITLE
Reverse logs.

### ISSUE THREAD

**Issue by 623637646** [Frezyx/talker#51]
Is it possible to reverse the order of the logs? It's earliest first, a bit hard to scroll to the bottom to see the newest logs.

**Comment by Frezyx** [comment]
Hello @623637646 ✋🏻 

Yes, it is realizable
In Talker data saved to history list. This list available in controller for TalkerFlutter. 
It's possible to make a method in the controller to reverse the list and the corresponding button in the UI

**Comment by 623637646** [comment]
Thanks for the great work. Will you release a new version soon? @Frezyx

**Comment by Frezyx** [comment]
Now this feature available in [1.2.0 version of talker_flutter](https://pub.dev/packages/talker_flutter/changelog)
