### ISSUE TITLE
"print" cut off my logs.

### ISSUE THREAD

**Issue by 623637646** [Frezyx/talker#63]
**Describe the bug**

"print" cut off my logs. 
It's related to a bug of flutter https://github.com/flutter/flutter/issues/110236

**To Reproduce**

Execute `flutter run` on the code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:talker/talker.dart';

void main() {
  Talker().info("""
┌────1──────────────────────────────────────────────────────────────────────────────────────────────────────────
┌─────2─────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────3───────────────────────────────────────────────────────────────────────────────────────────────────────
[LOG] | 0:14:30 55ms | 123123123131232131231231231231231231231231231231123123123131232131231231231231231231231
""");
}

```

</details>

**Expected results:**
The console prints my complete logs.

**Actual results:** 
The console only prints a portion of my logs.

**Screenshots**
<img width="1347" alt="Screenshot 2022-08-25 at 12 01 36 PM" src="https://user-images.githubusercontent.com/5275802/186571885-03f57e21-add8-4055-84e9-94fd6c7ca80d.png">

**Desktop (please complete the following information):**

Refer to flutter https://github.com/flutter/flutter/issues/110236

**Smartphone (please complete the following information):**

Refer to flutter https://github.com/flutter/flutter/issues/110236

**Additional context**

The solution is use "debugPrint" instead of "print" in "talker_logger.dart line 11".  But this needs talk_logger to be dependent on flutter SDK. I don't know what's the best solution. so post the issue here instead of sending the pull request. 
<img width="1210" alt="Screenshot 2022-08-25 at 12 07 15 PM" src="https://user-images.githubusercontent.com/5275802/186572592-fac542b8-481d-4ab4-9b34-d007f9cd00fa.png">

**Comment by Frezyx** [comment]
Hello @623637646 !
Yes you right! 
This is an unpleasant bug that I didn't get around to.

Solution for fix it is provide output method from talker_flutter to talker_logger
![telegram-cloud-photo-size-2-5204108007825326212-y](https://user-images.githubusercontent.com/40857927/186588366-01bbb947-5e40-404c-82c9-7d64ec20f3db.jpg)

**Comment by Frezyx** [comment]
I can do it, but later. Busy with work right now
I will be happy if you can help with this 👍🏻

**Comment by probka00** [comment]
@Frezyx @623637646 
Hey!
I fixed that problem in this PR https://github.com/Frezyx/talker/pull/64

**Comment by Frezyx** [comment]
@623637646 Now you can provide debugPrint as output method via output field in Talker constructor

**Comment by Frezyx** [comment]
I will think about better solution in near future
The main task is to understand at the talker_flutter package level a flutter or dart application is used right now and use the debugPrint method as default if it is flutter application.

**Comment by 623637646** [comment]
Sorry, I was also busy with work. This was my solution (before the pull request https://github.com/Frezyx/talker/pull/64 ).
```
Talker(
  logger: TalkerLogger(
    output: debugPrint,  // add this to avoid this issue.
    settings: TalkerLoggerSettings(
      // disable colors in iOS due to https://github.com/flutter/flutter/issues/20663
      enableColors: !Platform.isIOS,
    ),
  ),
)
```
Thanks, guys for the great effort.
