### ISSUE TITLE
Snackbar shows null as message in TalkerWrapper

### ISSUE THREAD

**Issue by alberto-paiva** [Frezyx/talker#70]
First: congratulations for this excellent work!

This error occurs in the talker_flutter version: 2.0.0+1.

**Describe the bug**
When an exception occurs, the message in the Snackbar is null.

Example:

```dart
 void _handleException() {
    try {
      throw Exception('Test Exception');
    } catch (e, st) {
      talker.handle(e, st);
    }
  }
```
**Screenshots**
![Captura de tela de 2022-10-03 13-55-22](https://user-images.githubusercontent.com/14572444/193639300-b52fdc7f-9528-47ec-bccf-dce5babfeaa0.png)

I believe this error is being caused by the 'SnackbarContent on file: talker_flutter/lib/src/ui/talker_wrapper/talker_wrapper.dart method. 

![Captura de tela de 2022-10-03 14-13-15](https://user-images.githubusercontent.com/14572444/193638170-10be894c-77c1-4408-8ca5-cd158c121349.png)

I think the correct one would be:   ` message: data.exception.toString(),`

```dart
                SnackbarContent(
                  message: data.exception.toString(),
                  title: options.errorTitle,
                ),
```

After changing to ` message: data.exception.toString(),`  it works.

![Captura de tela de 2022-10-03 14-08-13](https://user-images.githubusercontent.com/14572444/193639559-215ca345-1537-4e99-9da0-4e092e8c9007.png)

**Comment by Frezyx** [comment]
Resolved in [3.0.0 Release](https://github.com/Frezyx/talker/pull/108)
Please reopen the issue if you have any further questions or if the bug has not been fixed ❤️
