### ISSUE TITLE
Response color customization.

### ISSUE THREAD

**Issue by zakaria5729** [Frezyx/talker#81]
Please add the response (request, response) color customization option in [talker_dio_logger](https://pub.dev/packages/talker_dio_logger).

**Comment by Frezyx** [comment]
Hello @zakaria5729 !
Thank you for your suggestion!
I implement this functionality in 0.6.0 version of package [talker_dio_logger: ^0.6.0](https://pub.dev/packages/talker_dio_logger)

**Comment by Frezyx** [comment]
Now you can use 
**responsePen** and **requestPen**

**Comment by Frezyx** [comment]
More details you can find [here](https://pub.dev/packages/talker_dio_logger/changelog)
