### ISSUE TITLE
Use navigationObserver with auto_route package

### ISSUE THREAD

**Issue by Tokenizer94** [Frezyx/talker#93]
How can i use navigationObserver with auto_route package? 
MaterialApp.router has no parameter named navigationObserver. What can I do?

**Comment by Frezyx** [comment]
Hello @Tokenizer94 !
- MaterialApp.router has field named **routerDelegate**
- AutoRouterDelegate has field **navigatorObservers**
```dart
      routerDelegate: AutoRouterDelegate(
        _appRouter,
        navigatorObservers: () => [
          TalkerRouteObserver(talker),
        ],
      ),
```

**Comment by Tokenizer94** [comment]
Thanks alot
